### PR TITLE
implement CLI boilerplate

### PR DESCRIPTION
**Pull request by arthurvr**
Fix https://github.com/sindresorhus/node-module-boilerplate/issues/1. Same as the yeoman generator, in the `cli-boilerplate` folder.

### CODE REVIEW

**Comment by sindresorhus** [comment]
:+1:

**Comment by sindresorhus** [comment]
@kevva Any ideas how we can make `$ curl -fsSL https://github.com/sindresorhus/node-module-boilerplate/archive/master.tar.gz | tar -xz --strip-components 2` target only of of the folders?

**Comment by kevva** [comment]
Yeah, `curl -fsSL https://github.com/sindresorhus/node-module-boile
rplate/archive/master.tar.gz | tar -xz node-module-boilerplate
-master/cli-boilerplate --strip-components 2` should do it.

**Comment by sindresorhus** [comment]
@kevva Awesome!

**Pull request merged**
